M48
; DRILL file {KiCad 9.0.5} date 2025-11-16T19:48:43+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-16T19:48:43+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X188.88Y-80.64
X188.88Y-86.42
T2
X107.56Y-43.92
X107.56Y-80.92
X174.56Y-43.92
X174.56Y-80.92
T3
X109.42Y-107.56
X190.4Y-107.45
M30
